export type PersonStatus = "alive" | "dead";

export interface MockPerson {
  id: string;
  name: string;
  age: number;
  photo: string | null;
  occupation: string;
  nationality: string;
  isPrivate: boolean;
  gender: "man" | "woman";
  status: PersonStatus;
  watcherCount: number;
  diedAt: string | null;
  notified: boolean;
  followedAt: string;
  wikidataId: string;
  group: string;
  groupSuggestions: string[];
}

export const MOCK_PEOPLE: MockPerson[] = [
  {
    id: "p1",
    name: "Taylor Swift",
    age: 34,
    photo: null,
    occupation: "Musician",
    nationality: "American",
    isPrivate: false,
    gender: "woman",
    status: "alive",
    watcherCount: 12847,
    diedAt: null,
    notified: false,
    followedAt: "2024-01-15",
    wikidataId: "Q26876",
    group: "Pop royalty",
    groupSuggestions: ["p3", "p9"],
  },
  {
    id: "p2",
    name: "Mick Jagger",
    age: 80,
    photo: null,
    occupation: "Musician",
    nationality: "British",
    isPrivate: false,
    gender: "man",
    status: "alive",
    watcherCount: 9234,
    diedAt: null,
    notified: false,
    followedAt: "2024-02-01",
    wikidataId: "Q128787",
    group: "Rock legends",
    groupSuggestions: ["p3", "p4"],
  },
  {
    id: "p3",
    name: "Dolly Parton",
    age: 78,
    photo: null,
    occupation: "Musician",
    nationality: "American",
    isPrivate: false,
    gender: "woman",
    status: "alive",
    watcherCount: 7891,
    diedAt: null,
    notified: false,
    followedAt: "2024-01-28",
    wikidataId: "Q180338",
    group: "Country icons",
    groupSuggestions: ["p1", "p5"],
  },
  {
    id: "p4",
    name: "King Charles III",
    age: 76,
    photo: null,
    occupation: "Monarch",
    nationality: "British",
    isPrivate: false,
    gender: "man",
    status: "alive",
    watcherCount: 15203,
    diedAt: null,
    notified: false,
    followedAt: "2024-03-10",
    wikidataId: "Q43274",
    group: "The Firm",
    groupSuggestions: ["p2", "p5"],
  },
  {
    id: "p5",
    name: "Warren Buffett",
    age: 93,
    photo: null,
    occupation: "Investor",
    nationality: "American",
    isPrivate: false,
    gender: "man",
    status: "alive",
    watcherCount: 18920,
    diedAt: null,
    notified: false,
    followedAt: "2024-01-05",
    wikidataId: "Q47213",
    group: "Finance titans",
    groupSuggestions: ["p4", "p2"],
  },
  {
    id: "p6",
    name: "Betty White",
    age: 99,
    photo: null,
    occupation: "Actress",
    nationality: "American",
    isPrivate: false,
    gender: "woman",
    status: "dead",
    watcherCount: 31045,
    diedAt: "2021-12-31",
    notified: true,
    followedAt: "2020-06-01",
    wikidataId: "Q232394",
    group: "Golden age TV",
    groupSuggestions: ["p3", "p5"],
  },
  {
    id: "p7",
    name: "Henry Kissinger",
    age: 100,
    photo: null,
    occupation: "Diplomat",
    nationality: "American",
    isPrivate: false,
    gender: "man",
    status: "dead",
    watcherCount: 8712,
    diedAt: "2023-11-29",
    notified: false,
    followedAt: "2020-01-01",
    wikidataId: "Q66107",
    group: "Cold War figures",
    groupSuggestions: ["p4", "p5"],
  },
  {
    id: "p8",
    name: "Margaret T.",
    age: 84,
    photo: null,
    occupation: "Private individual",
    nationality: "American",
    isPrivate: true,
    gender: "woman",
    status: "alive",
    watcherCount: 1,
    diedAt: null,
    notified: false,
    followedAt: "2024-02-14",
    wikidataId: "",
    group: "",
    groupSuggestions: [],
  },
  // Search-only results (not yet followed)
  {
    id: "p9",
    name: "Beyoncé",
    age: 42,
    photo: null,
    occupation: "Musician",
    nationality: "American",
    isPrivate: false,
    gender: "woman",
    status: "alive",
    watcherCount: 22103,
    diedAt: null,
    notified: false,
    followedAt: "",
    wikidataId: "Q42723",
    group: "Pop royalty",
    groupSuggestions: ["p1", "p3"],
  },
  {
    id: "p10",
    name: "Rupert Murdoch",
    age: 93,
    photo: null,
    occupation: "Media mogul",
    nationality: "Australian",
    isPrivate: false,
    gender: "man",
    status: "alive",
    watcherCount: 11482,
    diedAt: null,
    notified: false,
    followedAt: "",
    wikidataId: "Q53946",
    group: "Media moguls",
    groupSuggestions: ["p5", "p4"],
  },
];

export const INITIAL_FOLLOWING = new Set(["p1", "p2", "p3", "p4", "p5", "p6", "p7", "p8"]);
